- name: install docker
  ansible.builtin.package:
    name: docker
    state: present

- name: Pull an image
  community.docker.docker_image_pull:
    name: haproxy
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    platform: amd64

- name: Generating HAproxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "/opt/haproxy.cfg"
    mode: '0644'

- name: Run HAProxy container
  community.docker.docker_container:
    name: haproxy
    image: haproxy
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes: "/opt/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
