- name: Conection to vm test playbook
  hosts: nginx_primary
  vars:
    base_path: /srv/www
    pages:
      page1:
        title: in intersting title
        content: Words and stuff
        path: test.html
      page2:
        title: va vagrefgvat gvgyr
        content: Jbeqf naq fghss
        path: grfg.html
  tasks:
    - name: dir test
      vars:
        page: "{{ pages.page1 }}"
      debug:
        msg: "{{ base_path }}/{{page.path}}"

    - name: content test
      vars:
        page: "{{ pages.page2 }}"
      debug:
        msg: "{{ page }}"

    - name: Using dict2items
      vars:
        page: "{{ item.value }}"
      ansible.builtin.debug:
        msg: "{{ page }}"
      loop: "{{ pages | dict2items }}"

    - name: test getting pi
      ansible.builtin.debug:
        msg: "{{ groups['nginx_primary'][0] }}"
